# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 8088, host: 8088
  config.vm.network "forwarded_port", guest: 3306, host: 3306

  config.vm.synced_folder "../", "/vagrant_data"
  config.vm.synced_folder "../sakila-db", "/sakila"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    /bin/bash /vagrant_data/install.sh
    /bin/bash /vagrant_data/start.sh
  SHELL
end
