# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.define "master" do |m|
    m.vm.box = "ubuntu/bionic64"

    config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end

    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y puppetmaster
    SHELL

  end

  # (1..1).each do |i|
  #   config.vm.define "node-#{i}" do |m|
  #     m.vm.box = "ubuntu/bionic64"

  #     config.vm.provider "virtualbox" do |vb|
  #       vb.memory = "1024"
  #     end

  #     config.vm.provision "shell", inline: <<-SHELL
  #       sudo apt-get update
  #       sudo apt-get install -y puppet
  #     SHELL

  #   end
  # end
end
