branches:
  only:
    - master
sudo: required
language: node_js
node_js:
  - "4"
services:
  - docker
install:
  - npm install -g grunt-cli
  - npm install
  - npm test
after_success:
  - export V_MAJOR=0
  - export V_MINOR=1
  - export VERSION=$V_MAJOR.$V_MINOR.$TRAVIS_BUILD_NUMBER
  - echo $VERSION
  - ls
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -f Dockerfile -t diegoluiz/node-sample:$VERSION -t diegoluiz/node-sample:latest .
  - docker push diegoluiz/node-sample